// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs2aNrCPxyXcFx8nzKs0hygZtik9vqAdE',
    appId: '1:322270828913:web:780b247fc7b752387a3ed0',
    messagingSenderId: '322270828913',
    projectId: 'powerapps-91dfd',
    authDomain: 'powerapps-91dfd.firebaseapp.com',
    storageBucket: 'powerapps-91dfd.appspot.com',
    measurementId: 'G-0VNFVPK050',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIF7yFw5gCmFQgI0fb-pRAFC1ZwGERhAE',
    appId: '1:322270828913:android:aa0eb4220f7dba6d7a3ed0',
    messagingSenderId: '322270828913',
    projectId: 'powerapps-91dfd',
    storageBucket: 'powerapps-91dfd.appspot.com',
  );
}
